/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import {
  CustomerProfile,
  CustomerProfileCreate,
} from './dtos/CustomerProfile.dto';
import { CustomerProfileController } from './CustomerProfile.controller';
import { CustomerProfileService } from './CustomerProfile.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('CustomerProfileController', () => {
  let controller: CustomerProfileController;
  let spyService: CustomerProfileService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: CustomerProfileService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [CustomerProfileController],
      providers: [CustomerProfileService, ApiServiceProvider],
    }).compile();

    controller = module.get<CustomerProfileController>(
      CustomerProfileController,
    );
    spyService = module.get<CustomerProfileService>(CustomerProfileService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call CustomerProfileController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call CustomerProfileController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new CustomerProfile();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
