/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { CustomerProfile } from './CustomerProfile.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { CustomerProfileService } from './CustomerProfile.service';
import { CustomerProfileController } from './CustomerProfile.controller';

@Module({
  imports: [TypeOrmModule.forFeature([CustomerProfile])],
  providers: [CustomerProfileService],
  exports: [CustomerProfileService],
  controllers: [CustomerProfileController],
})
export class CustomerProfileModule {}
