/**
 * This file generated by Apso.
 */
import { Controller } from '@nestjs/common';
import {
  Crud,
  CrudController,
  Override,
  ParsedRequest,
  CrudRequest,
  ParsedBody,
  CreateManyDto,
} from '@nestjsx/crud';
import { ApiTags, ApiResponse, ApiOperation, ApiBody } from '@nestjs/swagger';
import {
  CustomerProfile,
  CustomerProfileCreate,
} from './dtos/CustomerProfile.dto';
import { CustomerProfileService } from './CustomerProfile.service';

@Crud({
  model: {
    type: CustomerProfile,
  },
  dto: {
    create: CustomerProfileCreate,
    update: CustomerProfile,
    replace: CustomerProfile,
  },
  query: {
    /**
     * commenting out limit and pagination because of an issue with Crud lib: https://github.com/nestjsx/crud/issues/777
     */
    // TODO: make limit env driven?
    limit: 5,
    alwaysPaginate: true,
  },
})
@Controller('CustomerProfiles')
@ApiTags('CustomerProfiles')
export class CustomerProfileController
  implements CrudController<CustomerProfile>
{
  constructor(public service: CustomerProfileService) {}

  get base(): CrudController<CustomerProfile> {
    return this;
  }

  @Override('getManyBase')
  @ApiOperation({ summary: 'Retrieve multiple CustomerProfiles' })
  getMany(@ParsedRequest() req: CrudRequest) {
    return this.base.getManyBase(req);
  }

  @Override('getOneBase')
  @ApiOperation({ summary: 'Retrieve a single CustomerProfile' })
  get(@ParsedRequest() req: CrudRequest) {
    return this.base.getOneBase(req);
  }

  @Override('createOneBase')
  @ApiOperation({ summary: 'Create a single CustomerProfile' })
  @ApiBody({
    type: CustomerProfileCreate,
    description:
      'The Description for the Post Body. Please look into the DTO. You will see the @ApiOptionalProperty used to define the Schema.',
  })
  create(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: CustomerProfile,
  ) {
    return this.base.createOneBase(req, dto);
  }

  @Override('createManyBase')
  @ApiOperation({ summary: 'Create multipleCustomerProfiles' })
  createMany(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: CreateManyDto<CustomerProfile>,
  ) {
    return this.base.createManyBase(req, dto);
  }

  @Override('updateOneBase')
  @ApiOperation({ summary: 'Update a single CustomerProfile' })
  update(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: CustomerProfile,
  ) {
    return this.base.updateOneBase(req, dto);
  }

  @Override('replaceOneBase')
  @ApiOperation({ summary: 'Replace a single CustomerProfile' })
  replace(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: CustomerProfile,
  ) {
    return this.base.replaceOneBase(req, dto);
  }

  @Override('deleteOneBase')
  @ApiOperation({ summary: 'Delete a single CustomerProfile' })
  delete(@ParsedRequest() req: CrudRequest) {
    return this.base.deleteOneBase(req);
  }
}
