/**
 * This file generated by Apso.
 */
import { SubscriptionModule } from './Subscription/Subscription.module';
import { PlanModule } from './Plan/Plan.module';
import { CustomerProfileModule } from './CustomerProfile/CustomerProfile.module';

export default [SubscriptionModule, PlanModule, CustomerProfileModule];
