import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class CustomerProfileCreate {
  @ApiProperty()
  name: string;
  @ApiProperty()
  email: string;
  @ApiProperty()
  phone_number: string;
  @ApiProperty()
  address: string;
}

export class CustomerProfile {
  @ApiProperty()
  id: number;
  @ApiProperty()
  name: string;
  @ApiProperty()
  email: string;
  @ApiProperty()
  phone_number: string;
  @ApiProperty()
  address: string;
}
